/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CameraSettings {
  'iso' : bigint,
  'focus' : bigint,
  'exposure' : bigint,
  'sharpness' : bigint,
  'torchOn' : boolean,
  'imageQuality' : bigint,
  'contrast' : bigint,
  'flip' : boolean,
  'zoom' : bigint,
  'mirror' : boolean,
  'shutterSpeed' : bigint,
  'brightness' : bigint,
  'colorTemperature' : bigint,
  'resolution' : bigint,
  'cameraDeviceId' : string,
  'gridOverlay' : boolean,
  'whiteBalance' : { 'custom' : bigint } |
    { 'auto' : null },
  'saturation' : bigint,
  'aspectRatio' : { 'ratio1_1' : null } |
    { 'ratio4_3' : null } |
    { 'ratio16_9' : null },
}
export interface Feedback {
  'review' : [] | [string],
  'user' : Principal,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface Preset { 'name' : string, 'settings' : CameraSettings }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePreset' : ActorMethod<[string], undefined>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAverageRating' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPreset' : ActorMethod<[string], Preset>,
  'getPresets' : ActorMethod<[], Array<Preset>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], CameraSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetUserSettings' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePreset' : ActorMethod<[string, CameraSettings], undefined>,
  'saveUserSettings' : ActorMethod<[CameraSettings], undefined>,
  'submitFeedback' : ActorMethod<[bigint, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];