/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Feedback = IDL.Record({
  'review' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CameraSettings = IDL.Record({
  'iso' : IDL.Nat,
  'focus' : IDL.Nat,
  'exposure' : IDL.Int,
  'sharpness' : IDL.Int,
  'torchOn' : IDL.Bool,
  'imageQuality' : IDL.Nat,
  'contrast' : IDL.Int,
  'flip' : IDL.Bool,
  'zoom' : IDL.Nat,
  'mirror' : IDL.Bool,
  'shutterSpeed' : IDL.Nat,
  'brightness' : IDL.Int,
  'colorTemperature' : IDL.Nat,
  'resolution' : IDL.Nat,
  'cameraDeviceId' : IDL.Text,
  'gridOverlay' : IDL.Bool,
  'whiteBalance' : IDL.Variant({ 'custom' : IDL.Nat, 'auto' : IDL.Null }),
  'saturation' : IDL.Int,
  'aspectRatio' : IDL.Variant({
    'ratio1_1' : IDL.Null,
    'ratio4_3' : IDL.Null,
    'ratio16_9' : IDL.Null,
  }),
});
export const Preset = IDL.Record({
  'name' : IDL.Text,
  'settings' : CameraSettings,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePreset' : IDL.Func([IDL.Text], [], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAverageRating' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
  'getPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [CameraSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetUserSettings' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePreset' : IDL.Func([IDL.Text, CameraSettings], [], []),
  'saveUserSettings' : IDL.Func([CameraSettings], [], []),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Feedback = IDL.Record({
    'review' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CameraSettings = IDL.Record({
    'iso' : IDL.Nat,
    'focus' : IDL.Nat,
    'exposure' : IDL.Int,
    'sharpness' : IDL.Int,
    'torchOn' : IDL.Bool,
    'imageQuality' : IDL.Nat,
    'contrast' : IDL.Int,
    'flip' : IDL.Bool,
    'zoom' : IDL.Nat,
    'mirror' : IDL.Bool,
    'shutterSpeed' : IDL.Nat,
    'brightness' : IDL.Int,
    'colorTemperature' : IDL.Nat,
    'resolution' : IDL.Nat,
    'cameraDeviceId' : IDL.Text,
    'gridOverlay' : IDL.Bool,
    'whiteBalance' : IDL.Variant({ 'custom' : IDL.Nat, 'auto' : IDL.Null }),
    'saturation' : IDL.Int,
    'aspectRatio' : IDL.Variant({
      'ratio1_1' : IDL.Null,
      'ratio4_3' : IDL.Null,
      'ratio16_9' : IDL.Null,
    }),
  });
  const Preset = IDL.Record({ 'name' : IDL.Text, 'settings' : CameraSettings });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePreset' : IDL.Func([IDL.Text], [], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAverageRating' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
    'getPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [CameraSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetUserSettings' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePreset' : IDL.Func([IDL.Text, CameraSettings], [], []),
    'saveUserSettings' : IDL.Func([CameraSettings], [], []),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };