/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CameraSettings {
    iso: bigint;
    focus: bigint;
    exposure: bigint;
    sharpness: bigint;
    torchOn: boolean;
    imageQuality: bigint;
    contrast: bigint;
    flip: boolean;
    zoom: bigint;
    mirror: boolean;
    shutterSpeed: bigint;
    brightness: bigint;
    colorTemperature: bigint;
    resolution: bigint;
    cameraDeviceId: string;
    gridOverlay: boolean;
    whiteBalance: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "auto";
        auto: null;
    };
    saturation: bigint;
    aspectRatio: Variant_ratio1_1_ratio4_3_ratio16_9;
}
export type Time = bigint;
export interface Preset {
    name: string;
    settings: CameraSettings;
}
export interface UserProfile {
    name: string;
}
export interface Feedback {
    review?: string;
    user: Principal;
    timestamp: Time;
    rating: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_ratio1_1_ratio4_3_ratio16_9 {
    ratio1_1 = "ratio1_1",
    ratio4_3 = "ratio4_3",
    ratio16_9 = "ratio16_9"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deletePreset(name: string): Promise<void>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAverageRating(): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPreset(name: string): Promise<Preset>;
    getPresets(): Promise<Array<Preset>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSettings(): Promise<CameraSettings>;
    isCallerAdmin(): Promise<boolean>;
    resetUserSettings(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePreset(name: string, settings: CameraSettings): Promise<void>;
    saveUserSettings(settings: CameraSettings): Promise<void>;
    submitFeedback(rating: bigint, review: string | null): Promise<void>;
}
import type { CameraSettings as _CameraSettings, Feedback as _Feedback, Preset as _Preset, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePreset(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreset(arg0);
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreset(arg0: string): Promise<Preset> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreset(arg0);
                return from_candid_Preset_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreset(arg0);
            return from_candid_Preset_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresets(): Promise<Array<Preset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresets();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresets();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<CameraSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_CameraSettings_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_CameraSettings_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetUserSettings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserSettings();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePreset(arg0: string, arg1: CameraSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreset(arg0, to_candid_CameraSettings_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreset(arg0, to_candid_CameraSettings_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveUserSettings(arg0: CameraSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(to_candid_CameraSettings_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(to_candid_CameraSettings_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFeedback(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CameraSettings_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CameraSettings): CameraSettings {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Feedback_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Preset_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Preset): Preset {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    settings: _CameraSettings;
}): {
    name: string;
    settings: CameraSettings;
} {
    return {
        name: value.name,
        settings: from_candid_CameraSettings_n12(_uploadFile, _downloadFile, value.settings)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    iso: bigint;
    focus: bigint;
    exposure: bigint;
    sharpness: bigint;
    torchOn: boolean;
    imageQuality: bigint;
    contrast: bigint;
    flip: boolean;
    zoom: bigint;
    mirror: boolean;
    shutterSpeed: bigint;
    brightness: bigint;
    colorTemperature: bigint;
    resolution: bigint;
    cameraDeviceId: string;
    gridOverlay: boolean;
    whiteBalance: {
        custom: bigint;
    } | {
        auto: null;
    };
    saturation: bigint;
    aspectRatio: {
        ratio1_1: null;
    } | {
        ratio4_3: null;
    } | {
        ratio16_9: null;
    };
}): {
    iso: bigint;
    focus: bigint;
    exposure: bigint;
    sharpness: bigint;
    torchOn: boolean;
    imageQuality: bigint;
    contrast: bigint;
    flip: boolean;
    zoom: bigint;
    mirror: boolean;
    shutterSpeed: bigint;
    brightness: bigint;
    colorTemperature: bigint;
    resolution: bigint;
    cameraDeviceId: string;
    gridOverlay: boolean;
    whiteBalance: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "auto";
        auto: null;
    };
    saturation: bigint;
    aspectRatio: Variant_ratio1_1_ratio4_3_ratio16_9;
} {
    return {
        iso: value.iso,
        focus: value.focus,
        exposure: value.exposure,
        sharpness: value.sharpness,
        torchOn: value.torchOn,
        imageQuality: value.imageQuality,
        contrast: value.contrast,
        flip: value.flip,
        zoom: value.zoom,
        mirror: value.mirror,
        shutterSpeed: value.shutterSpeed,
        brightness: value.brightness,
        colorTemperature: value.colorTemperature,
        resolution: value.resolution,
        cameraDeviceId: value.cameraDeviceId,
        gridOverlay: value.gridOverlay,
        whiteBalance: from_candid_variant_n14(_uploadFile, _downloadFile, value.whiteBalance),
        saturation: value.saturation,
        aspectRatio: from_candid_variant_n15(_uploadFile, _downloadFile, value.aspectRatio)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    review: [] | [string];
    user: Principal;
    timestamp: _Time;
    rating: bigint;
}): {
    review?: string;
    user: Principal;
    timestamp: Time;
    rating: bigint;
} {
    return {
        review: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.review)),
        user: value.user,
        timestamp: value.timestamp,
        rating: value.rating
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: bigint;
} | {
    auto: null;
}): {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "auto";
    auto: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "auto" in value ? {
        __kind__: "auto",
        auto: value.auto
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ratio1_1: null;
} | {
    ratio4_3: null;
} | {
    ratio16_9: null;
}): Variant_ratio1_1_ratio4_3_ratio16_9 {
    return "ratio1_1" in value ? Variant_ratio1_1_ratio4_3_ratio16_9.ratio1_1 : "ratio4_3" in value ? Variant_ratio1_1_ratio4_3_ratio16_9.ratio4_3 : "ratio16_9" in value ? Variant_ratio1_1_ratio4_3_ratio16_9.ratio16_9 : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Preset>): Array<Preset> {
    return value.map((x)=>from_candid_Preset_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n4(_uploadFile, _downloadFile, x));
}
function to_candid_CameraSettings_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraSettings): _CameraSettings {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    iso: bigint;
    focus: bigint;
    exposure: bigint;
    sharpness: bigint;
    torchOn: boolean;
    imageQuality: bigint;
    contrast: bigint;
    flip: boolean;
    zoom: bigint;
    mirror: boolean;
    shutterSpeed: bigint;
    brightness: bigint;
    colorTemperature: bigint;
    resolution: bigint;
    cameraDeviceId: string;
    gridOverlay: boolean;
    whiteBalance: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "auto";
        auto: null;
    };
    saturation: bigint;
    aspectRatio: Variant_ratio1_1_ratio4_3_ratio16_9;
}): {
    iso: bigint;
    focus: bigint;
    exposure: bigint;
    sharpness: bigint;
    torchOn: boolean;
    imageQuality: bigint;
    contrast: bigint;
    flip: boolean;
    zoom: bigint;
    mirror: boolean;
    shutterSpeed: bigint;
    brightness: bigint;
    colorTemperature: bigint;
    resolution: bigint;
    cameraDeviceId: string;
    gridOverlay: boolean;
    whiteBalance: {
        custom: bigint;
    } | {
        auto: null;
    };
    saturation: bigint;
    aspectRatio: {
        ratio1_1: null;
    } | {
        ratio4_3: null;
    } | {
        ratio16_9: null;
    };
} {
    return {
        iso: value.iso,
        focus: value.focus,
        exposure: value.exposure,
        sharpness: value.sharpness,
        torchOn: value.torchOn,
        imageQuality: value.imageQuality,
        contrast: value.contrast,
        flip: value.flip,
        zoom: value.zoom,
        mirror: value.mirror,
        shutterSpeed: value.shutterSpeed,
        brightness: value.brightness,
        colorTemperature: value.colorTemperature,
        resolution: value.resolution,
        cameraDeviceId: value.cameraDeviceId,
        gridOverlay: value.gridOverlay,
        whiteBalance: to_candid_variant_n19(_uploadFile, _downloadFile, value.whiteBalance),
        saturation: value.saturation,
        aspectRatio: to_candid_variant_n20(_uploadFile, _downloadFile, value.aspectRatio)
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "auto";
    auto: null;
}): {
    custom: bigint;
} | {
    auto: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "auto" ? {
        auto: value.auto
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_ratio1_1_ratio4_3_ratio16_9): {
    ratio1_1: null;
} | {
    ratio4_3: null;
} | {
    ratio16_9: null;
} {
    return value == Variant_ratio1_1_ratio4_3_ratio16_9.ratio1_1 ? {
        ratio1_1: null
    } : value == Variant_ratio1_1_ratio4_3_ratio16_9.ratio4_3 ? {
        ratio4_3: null
    } : value == Variant_ratio1_1_ratio4_3_ratio16_9.ratio16_9 ? {
        ratio16_9: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
